package testapp;


/**
* testapp/Test1Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test1.idl
* jeudi 10 octobre 2024 18 h 15 CEST
*/

public interface Test1Operations 
{
  boolean signup (String username, String password);
  boolean login (String username, String password);
  String getUserStats (String username);

  // New method to get user stats
  void updateUserStats (String username, int wins, int draws, int losses);

  // New method to update user stats
  void shutdown ();
} // interface Test1Operations
