package testapp;


/**
* testapp/Test1.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test1.idl
* jeudi 10 octobre 2024 18 h 15 CEST
*/

public interface Test1 extends Test1Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Test1
